resume:
    resource: "@ResumeBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /app
    
    
easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin2
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
