<?php

namespace ResumeBundle\Repository;

/**
 * ExperienceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExperienceRepository extends \Doctrine\ORM\EntityRepository {

    public function getLastExp() {


        $qb = $this->createQueryBuilder("e")
                ->where('e.active = TRUE')
                ->orderBy('e.fin', 'DESC');

        $query = $qb->getQuery();
        return $query->getResult();
    }

}
